version: "3.7"
services:
  dbmysql:
    image: "mysql:5.6"
    container_name: dbmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
