version: "3.7"

services:
  backend:
    container_name: Kaddem
    build:
      context: ../5TWIN6-G1-KADDEM-DevOps
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.159.128:3306/kaddemApp?createDatabaseIfNotExist=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    image: azizbenhmida/kaddem:2.0.0

  angular-app:
    image: azizbenhmida/front:2.0.0
    ports:
      - "4200:80"
    restart: always
